from decimal import Decimal

CATEGORY_NAME_LEN = 32
CATEGORY_SLUG_LEN = 32
SUBCATEGORY_NAME_LEN = 32
SUBCATEGORY_SLUG_LEN = 32
PRODUCT_NAME_LEN = 256
PRODUCT_SLUG_LEN = 256
PRICE_MAX = Decimal(9999)
PRICE_LEN = len(str(PRICE_MAX)) + 2
SHOPPING_CART_MAX = 999
PAGE_SIZE = 10
